# These are supported funding model platforms
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: SiMokraneSIAD
ko_fi: simokranesiad
liberapay: SiMokraneSIAD
buy_me_a_coffee: SiMokraneSIAD
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
