# .github/workflows/metrics.yml
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          
          # This configuration creates a wide, multi-column layout
          template: notable
          config_display: wide
          base: header
          
          # All working plugins
          plugin_achievements: no
          plugin_discussions: yes
          plugin_followup: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_languages: yes
          plugin_people: yes
          plugin_reactions: yes
          plugin_traffic: yes