# .github/workflows/metrics.yml
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs once a day at midnight UTC
  workflow_dispatch: # Allows manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # ✅ Corrected to use your secret key name
          token: ${{ secrets.GH_TOKEN }}

          # OPTIONS
          template: classic
          base: header, activity, community, repositories, metadata
          
          # ENABLE ALL INTERESTING PLUGINS
          plugin_achievements: no
          plugin_discussions: yes
          plugin_followup: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_traffic: yes