# .github/workflows/metrics.yml
name: Metrics - Corrected Test
on:
  workflow_dispatch: # Manual runs only for this test

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          
          # ✅ CORRECTED parameter name
          committer_branch: metrics-render
          
          # PLUGINS
          # ✅ DISABLED the failing plugin
          plugin_achievements: no
          
          # All other plugins will still run
          plugin_discussions: yes
          plugin_followup: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_traffic: yes