name: Auto-add & Update Repo Traffic Badges

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get all public repos & update badges
        run: |
          README_FILE="README.md"
          TMP_FILE="README.tmp"

          cp "$README_FILE" "$TMP_FILE"

          # Fetch list of your public repos
          REPOS=$(curl -s -H "Authorization: token ${{ secrets.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 }}" \
            "https://api.github.com/user/repos?visibility=public&per_page=100" \
            | jq -r '.[].name')

          for REPO in $REPOS; do
            echo "Processing $REPO..."

            # Get traffic views
            RESPONSE=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.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 }}" \
              https://api.github.com/repos/${{ github.repository_owner }}/$REPO/traffic/views)

            TOTAL=$(echo "$RESPONSE" | jq '.count')

            # Badge markdown
            BADGE_MD="![${REPO} Views](https://img.shields.io/badge/${REPO}_Views-${TOTAL}-blue)"

            # Escape slashes for grep/sed
            ESCAPED_REPO=$(echo "$REPO" | sed 's/\//\\\//g')

            # If badge exists → update; else → add at the bottom of the README
            if grep -q "${REPO}_Views-" "$TMP_FILE"; then
              sed -i "s|https://img.shields.io/badge/${ESCAPED_REPO}_Views-[0-9]\+-blue|https://img.shields.io/badge/${REPO}_Views-${TOTAL}-blue|" "$TMP_FILE"
            else
              echo "$BADGE_MD" >> "$TMP_FILE"
            fi
          done

          mv "$TMP_FILE" "$README_FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update traffic badges" || echo "No changes"
          git push
