name: Update Repository Traffic Graph
on:
  schedule:
    # Runs "At 00:00" (midnight) every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  update_traffic_graph:
    runs-on: ubuntu-latest
    permissions:
      # This permission is needed for the action to commit the updated graph to your repository
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # This is your repository's built-in, secure token
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Specify the output file name
          filename: traffic.svg
          
          # We are disabling the default "base" metrics to only show the traffic plugin
          base: ""
          
          # Enable the traffic plugin
          plugins_traffic: yes