name: Auto-add & Update Repo Traffic Badges with Heading

on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare README and update badges
        run: |
          README="README.md"
          TMP="README.tmp"
          HEADING="## 📊 Repository Views"

          # Ensure the README has the heading; if not, add it at the end
          if ! grep -q "^$HEADING" "$README"; then
            echo -e "\n$HEADING\n" >> "$README"
          fi

          # Extract content before the heading
          sed "/^$HEADING/,\$d" "$README" > "$TMP"

          # Add the heading back
          echo -e "\n$HEADING\n" >> "$TMP"

          # Fetch all your public repos (max 100)
          REPOS=$(curl -s -H "Authorization: token ${{ secrets.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 }}" \
            "https://api.github.com/user/repos?visibility=public&per_page=100" \
            | jq -r '.[].name')

          # For each repo, get views and prepare badge markdown
          for REPO in $REPOS; do
            RESPONSE=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.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 }}" \
              "https://api.github.com/repos/${{ github.repository_owner }}/$REPO/traffic/views")

            TOTAL=$(echo "$RESPONSE" | jq '.count')

            BADGE="![${REPO} Views](https://img.shields.io/badge/${REPO}_Views-${TOTAL}-blue)"

            echo "$BADGE" >> "$TMP"
          done

          # Overwrite README with new content
          mv "$TMP" "$README"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Auto-update repository traffic badges"
          git push
