name: Update Traffic Badges for All My Public Repos

on:
  schedule:
    - cron: '0 0 * * *'   # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dashboard repo
        uses: actions/checkout@v4

      - name: Update README with traffic badges for all repos
        run: |
          README="README.md"
          TMP="README.tmp"
          HEADING="## 📊 Repository Views"

          # Add heading if missing
          if ! grep -q "^$HEADING" "$README"; then
            echo -e "\n$HEADING\n" >> "$README"
          fi

          # Preserve content above the heading
          sed "/^$HEADING/,\$d" "$README" > "$TMP"

          # Add the heading
          echo -e "\n$HEADING\n" >> "$TMP"

          # Get all your public repos
          REPOS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/user/repos?visibility=public&per_page=100" \
            | jq -r '.[].name')

          for REPO in $REPOS; do
            RESPONSE=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository_owner }}/$REPO/traffic/views")

            TOTAL=$(echo "$RESPONSE" | jq '.count')

            echo "![${REPO} Views](https://img.shields.io/badge/${REPO}_Views-${TOTAL}-blue)" >> "$TMP"
          done

          mv "$TMP" "$README"

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update traffic badges for all repos"
          git push
