name: Update Traffic Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allow manual run

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get traffic views
        id: traffic
        run: |
          RESPONSE=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.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 }}" \
            https://api.github.com/repos/${{ github.repository }}/traffic/views)

          TOTAL=$(echo "$RESPONSE" | jq '.count')
          echo "total_views=$TOTAL" >> $GITHUB_ENV

      - name: Update README badge
        run: |
          BADGE_URL="https://img.shields.io/badge/Views-${{ env.total_views }}-blue"
          sed -i "s|!\[Views\](.*)|![Views](${BADGE_URL})|" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update traffic badge" || echo "No changes"
          git push
